books_data = [
    {"id": 1, "title": "Dracula", "author": "Bram Stoker", "category": "Horror", "description": "Classic horror novel.", "price": "$9.99"},
    {"id": 2, "title": "Pride and Prejudice", "author": "Jane Austen", "category": "Drama", "description": "Romantic drama.", "price": "$12.99"},
    {"id": 3, "title": "The Hobbit", "author": "J.R.R. Tolkien", "category": "Storybook", "description": "Fantasy adventure.", "price": "$15.99"},
    {"id": 4, "title": "Cinderella", "author": "Charles Perrault", "category": "Fairytale", "description": "Classic fairytale.", "price": "$7.99"},
    {"id": 5, "title": "Steve Jobs", "author": "Walter Isaacson", "category": "Biography", "description": "Biography of Steve Jobs.", "price": "$20.99"},
    {"id": 6, "title": "Encyclopedia Britannica", "author": "Various", "category": "Encyclopedia", "description": "Comprehensive encyclopedia.", "price": "$100.00"},
    {"id": 7, "title": "The Science Book", "author": "DK", "category": "Science", "description": "Science concepts explained.", "price": "$25.00"},
    {"id": 8, "title": "The Art of War", "author": "Sun Tzu", "category": "Strategy", "description": "Ancient Chinese military treatise.", "price": "$10.99"},
    {"id": 9, "title": "1984", "author": "George Orwell", "category": "Dystopian", "description": "Dystopian social science fiction.", "price": "$14.99"},
    {"id": 10, "title": "To Kill a Mockingbird", "author": "Harper Lee", "category": "Drama", "description": "Pulitzer Prize-winning novel.", "price": "$11.99"},
    {"id": 11, "title": "Frankenstein", "author": "Mary Shelley", "category": "Horror", "description": "Classic gothic novel.", "price": "$8.99"},
    {"id": 12, "title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling", "category": "Fantasy", "description": "First book in the Harry Potter series.", "price": "$9.99"},
    {"id": 13, "title": "The Catcher in the Rye", "author": "J.D. Salinger", "category": "Fiction", "description": "Novel about teenage rebellion.", "price": "$10.99"},
    {"id": 14, "title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "category": "Classic", "description": "Novel set in the Jazz Age.", "price": "$10.99"},
    {"id": 15, "title": "Moby Dick", "author": "Herman Melville", "category": "Adventure", "description": "Epic sea story.", "price": "$12.99"},
    {"id": 16, "title": "War and Peace", "author": "Leo Tolstoy", "category": "Historical Fiction", "description": "Novel set during the Napoleonic Wars.", "price": "$15.99"},
    {"id": 17, "title": "The Odyssey", "author": "Homer", "category": "Epic", "description": "Ancient Greek epic poem.", "price": "$13.99"},
    {"id": 18, "title": "Hamlet", "author": "William Shakespeare", "category": "Drama", "description": "Shakespearean tragedy.", "price": "$8.99"},
    {"id": 19, "title": "The Iliad", "author": "Homer", "category": "Epic", "description": "Ancient Greek epic poem.", "price": "$13.99"},
    {"id": 20, "title": "A Brief History of Time", "author": "Stephen Hawking", "category": "Science", "description": "Introduction to cosmology.", "price": "$18.99"},
    {"id": 21, "title": "The Diary of a Young Girl", "author": "Anne Frank", "category": "Biography", "description": "Diary of Anne Frank during WWII.", "price": "$9.99"},
    {"id": 22, "title": "The Divine Comedy", "author": "Dante Alighieri", "category": "Classic", "description": "Epic poem about the afterlife.", "price": "$11.99"},
    {"id": 23, "title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "category": "Classic", "description": "Russian novel about morality.", "price": "$14.99"},
    {"id": 24, "title": "The Alchemist", "author": "Paulo Coelho", "category": "Adventure", "description": "Novel about a shepherd's journey.", "price": "$9.99"},
    {"id": 25, "title": "The Art of Computer Programming", "author": "Donald Knuth", "category": "Programming", "description": "Comprehensive book on algorithms.", "price": "$199.99"},
    {"id": 26, "title": "The Elements of Style", "author": "William Strunk Jr.", "category": "Writing", "description": "Guide to writing style.", "price": "$9.99"},
    {"id": 27, "title": "The Road", "author": "Cormac McCarthy", "category": "Post-Apocalyptic", "description": "Novel set in a post-apocalyptic world.", "price": "$12.99"},
    {"id": 28, "title": "The Little Prince", "author": "Antoine de Saint-Exupéry", "category": "Children's", "description": "Philosophical story for children.", "price": "$7.99"},
    {"id": 29, "title": "A Game of Thrones", "author": "George R.R. Martin", "category": "Fantasy", "description": "First book in the A Song of Ice and Fire series.", "price": "$14.99"},
    {"id": 30, "title": "The Wind-Up Bird Chronicle", "author": "Haruki Murakami", "category": "Fiction", "description": "Novel about a Tokyo man's search for his wife.", "price": "$16.99"},
]
